- name: launch a compute instance
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
  - name: launch an instance
    os_server:
      state: present
      name: vm1-ansible
      image: ea930841-ca66-475e-ae64-a0b3d540eb0e
#      key_name: bobbus
      flavor: 3
